steps:
# 1. (Optional) Run Terraform Init and Plan for validation
- name: 'hashicorp/terraform:latest'
  entrypoint: 'sh'
  args:
    - '-c'
    - |
      cd iac
      terraform init
      terraform plan -var="project_id=${PROJECT_ID}" -var="document_ai_processor_id=projects/${PROJECT_ID}/locations/eu/processors/${_DOCUMENT_AI_PROCESSOR_ID}"
  id: 'terraform-plan'

# 2. Deploy Frontend to GCS
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rsync', '-r', './frontend/', 'gs://${_FRONTEND_BUCKET_NAME}/']
  id: 'deploy-frontend'

# 3. Zip and Deploy Cloud Function
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'functions'
    - 'deploy'
    - 'match-resume'
    - '--runtime=python310'
    - '--trigger-http'
    - '--entry-point=match_resume'
    - '--source=./backend/cloud-function'
    - '--region=europe-west1' 
    - '--service-account=resume-matcher-cf-sa@${PROJECT_ID}.iam.gserviceaccount.com'
    - '--timeout=300s'
    - '--memory=512MB'
    - '--set-env-vars=KEYWORD_DATA_BUCKET=${_KEYWORD_DATA_BUCKET_NAME},DOCUMENT_AI_PROCESSOR_ID=projects/${PROJECT_ID}/locations/eu/processors/${_DOCUMENT_AI_PROCESSOR_ID}'
  id: 'deploy-cloud-function'

# 4. Upload Keyword Data (if not manually uploaded)
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', './keyword-data/*', 'gs://${_KEYWORD_DATA_BUCKET_NAME}/']
  id: 'upload-keyword-data'

logging: CLOUD_LOGGING_ONLY

substitutions:
  _FRONTEND_BUCKET_NAME: "resume-matcher-frontend" 
  _KEYWORD_DATA_BUCKET_NAME: "resume-matcher-keywords" 
  _DOCUMENT_AI_PROCESSOR_ID: "936d78612d21613"